/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#0053db",
        "primary-dim": "#0048c1",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#c7d3ff",
        "on-primary": "#f8f7ff",
        "on-primary-fixed": "#003798",
        "on-primary-fixed-variant": "#0050d4",
        "on-primary-container": "#0048bf",
        "primary-container": "#dbe1ff",
        "inverse-primary": "#618bff",
        secondary: "#5c605f",
        "secondary-dim": "#505453",
        "secondary-fixed": "#e0e3e2",
        "secondary-fixed-dim": "#d2d5d4",
        "on-secondary": "#f7f9f8",
        "on-secondary-fixed": "#3c4040",
        "on-secondary-fixed-variant": "#595c5c",
        "on-secondary-container": "#4f5252",
        "secondary-container": "#e0e3e2",
        tertiary: "#4a6552",
        "tertiary-dim": "#3e5946",
        "tertiary-fixed": "#daf9df",
        "tertiary-fixed-dim": "#cbead1",
        "on-tertiary": "#e7ffea",
        "on-tertiary-fixed": "#334e3b",
        "on-tertiary-fixed-variant": "#4f6b57",
        "on-tertiary-container": "#45604d",
        "tertiary-container": "#daf9df",
        error: "#9f403d",
        "error-dim": "#4e0309",
        "error-container": "#fe8983",
        "on-error": "#fff7f6",
        "on-error-container": "#752121",
        surface: "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "surface-dim": "#cfdce3",
        "surface-tint": "#0053db",
        "surface-variant": "#d9e4ea",
        "surface-container": "#e8eff3",
        "surface-container-low": "#f0f4f7",
        "surface-container-high": "#e1e9ee",
        "surface-container-highest": "#d9e4ea",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#2a3439",
        "on-surface-variant": "#566166",
        "on-background": "#2a3439",
        background: "#f7f9fb",
        outline: "#717c82",
        "outline-variant": "#a9b4b9",
        "inverse-surface": "#0b0f10",
        "inverse-on-surface": "#9a9d9f",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
