import { useState } from "react";

const RESIDUE_GROUPS = [
  {
    id: "ds_store",
    label: ".DS_Store files",
    desc: "Generated by macOS Finder. Safe to delete on Windows.",
    icon: "laptop_mac",
    count: 1_204,
    size: 2_100_000,
    builtin: true,
    enabled: true,
  },
  {
    id: "dot_underscore",
    label: "._* AppleDouble files",
    desc: "macOS resource fork files. Harmless but unnecessary on Windows.",
    icon: "laptop_mac",
    count: 847,
    size: 4_300_000,
    builtin: true,
    enabled: true,
  },
  {
    id: "thumbs_db",
    label: "Thumbs.db",
    desc: "Windows thumbnail cache. Regenerated automatically.",
    icon: "image",
    count: 312,
    size: 890_000,
    builtin: true,
    enabled: true,
  },
  {
    id: "desktop_ini",
    label: "desktop.ini",
    desc: "Windows folder customization files. Usually safe to remove.",
    icon: "settings",
    count: 203,
    size: 120_000,
    builtin: true,
    enabled: false,
  },
  {
    id: "tmp",
    label: "*.tmp / *.temp",
    desc: "Temporary files left by applications.",
    icon: "hourglass_empty",
    count: 89,
    size: 340_000_000,
    builtin: true,
    enabled: true,
  },
];

function formatBytes(b: number) {
  if (b < 1e6) return `${(b / 1e3).toFixed(0)} KB`;
  if (b < 1e9) return `${(b / 1e6).toFixed(1)} MB`;
  return `${(b / 1e9).toFixed(2)} GB`;
}

export default function ResidueTab() {
  const [rules, setRules] = useState(RESIDUE_GROUPS);
  const [selected, setSelected] = useState<Set<string>>(new Set(RESIDUE_GROUPS.filter((r) => r.enabled).map((r) => r.id)));

  function toggleRule(id: string) {
    setRules((prev) => prev.map((r) => (r.id === id ? { ...r, enabled: !r.enabled } : r)));
  }

  function toggleSelect(id: string) {
    setSelected((prev) => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  }

  const totalSelected = rules.filter((r) => selected.has(r.id)).reduce((s, r) => s + r.size, 0);

  return (
    <div className="px-8 py-6">
      <div className="space-y-3 mb-6">
        {rules.map((rule) => (
          <div
            key={rule.id}
            className="bg-surface-container-lowest rounded-xl border border-outline-variant/10 p-4 flex items-center gap-4"
          >
            <input
              type="checkbox"
              checked={selected.has(rule.id)}
              onChange={() => toggleSelect(rule.id)}
              className="w-4 h-4 rounded border-outline-variant text-primary focus:ring-primary/20"
            />
            <div className="w-10 h-10 rounded-lg bg-surface-container flex items-center justify-center shrink-0">
              <span className="material-symbols-outlined text-on-surface-variant text-[18px]">{rule.icon}</span>
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-sm font-semibold text-on-surface">{rule.label}</p>
              <p className="text-xs text-on-surface-variant mt-0.5">{rule.desc}</p>
              <p className="text-[10px] font-bold text-on-surface-variant/60 mt-1">
                {rule.count.toLocaleString()} files · {formatBytes(rule.size)}
              </p>
            </div>
            <div className="flex items-center gap-2 shrink-0">
              {rule.builtin && (
                <span className="text-[9px] font-bold uppercase tracking-widest text-on-surface-variant/40 bg-surface-container px-2 py-0.5 rounded">
                  Built-in
                </span>
              )}
              <button
                onClick={() => toggleRule(rule.id)}
                className={[
                  "relative w-10 h-5 rounded-full transition-colors",
                  rule.enabled ? "bg-primary" : "bg-surface-container-highest",
                ].join(" ")}
              >
                <span
                  className={[
                    "absolute top-0.5 w-4 h-4 rounded-full bg-white shadow transition-transform",
                    rule.enabled ? "translate-x-5" : "translate-x-0.5",
                  ].join(" ")}
                />
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Add custom rule */}
      <button className="w-full flex items-center justify-center gap-2 px-4 py-3 border-2 border-dashed border-outline-variant/30 rounded-xl text-sm font-semibold text-on-surface-variant hover:border-primary/30 hover:text-primary hover:bg-primary/5 transition-all mb-6">
        <span className="material-symbols-outlined text-[18px]">add</span>
        Add Custom Rule (glob / regex)
      </button>

      {/* Action bar */}
      {selected.size > 0 && (
        <div className="fixed bottom-6 left-1/2 -translate-x-1/2 glass-panel px-8 py-4 rounded-2xl shadow-2xl border border-white/30 flex items-center gap-8 z-50">
          <div>
            <p className="text-[10px] uppercase font-bold tracking-widest text-on-surface-variant">Selected</p>
            <p className="font-headline text-lg font-extrabold text-on-surface">
              {formatBytes(totalSelected)} · {selected.size} rule{selected.size > 1 ? "s" : ""}
            </p>
          </div>
          <button className="cta-gradient px-7 py-2.5 rounded-lg text-sm font-bold text-on-primary shadow-lg shadow-primary/20 flex items-center gap-2 active:scale-95 duration-150">
            <span className="material-symbols-outlined text-[18px]">delete_sweep</span>
            Move to Trash
          </button>
        </div>
      )}
    </div>
  );
}
